= AWS Cloud9でGAE/Goのコードを軽く書いてみる
:published_at: 2017-12-08
:hp-tags: Yagasaki,AWS,Cloud9,IDE

こんにちは！ +
いや〜激寒ですね！ +
八王子の朝は、いろいろ凍っております。 +
矢ヶ崎です。

== クラウドいろいろ

弊社では現在、AWSはもちろんのこと、Azure、GCP、Bluemixと、いろいろなクラウドプラットフォームを利用しています。 +
AWSのre:Inventには、うちの規模にしては贅沢に5名も！参加させていただきましたが、実はAWSだけ！という感じではありません。

しか〜し？！ +
AWS Cloud9という、素敵な開発環境がリリースされたではないですか！ +
こ、これは？！AWS！さすが！って思っているわけでございます。

== 開発環境への迷い

昨今のわたくしゴトですが、開発するにあたってのIDEやエディタというのに迷いがありました。 +
エディタは、vi(の機能しか使わない)ユーザだったのを、とうとうvimを使い始めたり、 +
やっぱりVSCodeがいいな〜って使い始めたり、 +
結局Eclipseだよね〜って戻ってみたり、 +
迷走中だった今日このごろ。 +
AWS Cloud9に出会い、これだ！っていうのに出会えちゃった感が無くならないうちに、ブログりたいと思います。

Cloud9は使ったことはあるのですが、個人的にはあくまで学習用のIDEっていうイメージが強かったのです。 +
しか〜し？！ +
AWS Cloud9では、自前のEC2があれこれできたり、AWS内なのでなんとなく安心という、あまり根拠の無い希望が湧いております！

== せっかくだから、Go(golang)のコードを試しに書いてみる

=== まずは立ち上げ

では、早速AWS Cloud9を使ってみましょう。

いつものように、クラスメソッドさんのブログを見れば、 +
AWSユーザなら誰でも簡単に立ち上げられます！

https://dev.classmethod.jp/cloud/aws/aws-reinvent-cloud9/

リージョンは、まだ東京に来ていないようなので、わたくしは同じアジアの
* Asia Pacific (Singapore)
を選択してみました。

公式のチュートリアルもあるので簡単ですね！

EC2のコンソールを見てみると、ちゃんとCloud9用のインスタンスが立ち上がってますね！

=== IDE画面をさわってみる

起動後に、「Open IDE」ボタンを押すと、それだけでIDE(統合開発環境)が表示されます。簡単ですね〜。

いわゆるIDEなので、Cloud9をさわったことが無い方でも、なんの違和感もなくさわれるかと思います！

画面下の方に、コンソールが表示される部分がありますので、それが自分用のCloud9のEC2の環境になります。 +
ここであれこれすれば、いろいろできちゃいますね〜。
![EC2の画面](画像のURL)


=== GoでHelloなんたら

では、Goのコードをちょろっと書いてみましょう。 +
AWS Cloud9では、デフォルトで最初からGoがサポートされている状態になってたので、 +
いきなり何も考えずにあれこれできます。

が！コードを書く前に、一応コンソールでGoのバージョンでも見てみますか。
![GoのVersion](画像のURL)


=== ついでにコラボってみる

コラボレーション機能的なのもついているので、 +
ペアプロ、モブプロ的なことをするのにも、とってもしやすそうです！ +
AWS Cloud9では、IAMユーザを作成し、Cloud9の操作権限を付与してあげれば、 +
IDEの右上の「Share」ボタンから簡単にコラボレーションが始められます！

こんな感じで、おのおの同時編集や、お互いに編集した箇所がわかりやすく表示されます。 +
koheくん、協力ありがとう！
![GoのVersion](画像のURL)

詳細は、安定のクラスメソッドブログがおすすめ！
https://dev.classmethod.jp/cloud/aws/aws-reinvent-cloud9-develop/






== 掟破り（？）のGAE/Goの開発環境にしてみる



== おしまい

これで、しばらくは快適な開発生活が送れます。 +
EC2の料金はかかってしまいますが、分単位のEC2課金と相まって大したコストもかからずに、 +
いつでもどこでも同じ開発環境が使えるということは非常に魅力を感じており、 +
しばらくはAWS Cloud9をメインにバリバリ開発をして行きたいという所存でございます。

=== 仕事でプログラムを機会がめっきり無いとしても！！！

以上


[Google先生](https://www.google.co.jp/)

![代替テキスト](画像のURL)
