= AWS Cloud9でGAE/Goのコードを軽く書いてみる
:published_at: 2017-12-08
:hp-tags: Yagasaki,AWS,Cloud9,IDE

こんにちは！ +
いや〜激寒ですね！ +
八王子の朝は、いろいろ凍っております。 +
矢ヶ崎です。

== クラウドいろいろ

弊社では現在、AWSはもちろんのこと、Azure、GCP、Bluemixと、いろいろなクラウドプラットフォームを利用しています。 +
AWSのre:Inventには、うちの規模にしては贅沢に5名も！参加させていただきましたが、実はAWSだけ！という感じではありません。

しか〜し？！ +
AWS Cloud9という、素敵な開発環境がリリースされたではないですか！ +
こ、これは？！AWS！さすが！って思っているわけでございます。

== 開発環境への迷い

昨今のわたくしゴトですが、開発するにあたってのIDEやエディタというのに迷いがありました。 +
エディタは、vi(の機能しか使わない)ユーザだったのを、とうとうvimを使い始めたり、 +
やっぱりVSCodeがいいな〜って使い始めたり、 +
結局Eclipseだよね〜って戻ってみたり、 +
迷走中だった今日このごろ。 +
AWS Cloud9に出会い、これだ！っていうのに出会えちゃった感が無くならないうちに、ブログりたいと思います。

Cloud9は使ったことはあるのですが、個人的にはあくまで学習用のIDEっていうイメージが強かったのです。 +
しか〜し？！ +
AWS Cloud9では、自前のEC2があれこれできたり、AWS内なのでなんとなく安心という、あまり根拠の無い希望が湧いております！

== せっかくだから、Go(golang)のコードを試しに書いてみる

== 掟破り（？）のGAE/Goの開発環境にしてみる



== おしまい

これで、しばらくは快適な開発生活が送れます。 +
EC2の料金はかかってしまいますが、分単位のEC2課金と相まって大したコストもかからずに、 +
いつでもどこでも同じ開発環境が使えるということは非常に魅力を感じており、 +
しばらくはAWS Cloud9をメインにバリバリ開発をして行きたいという所存でございます。

=== 仕事でプログラムを機会がめっきり無いとしても！！！

以上

