= 「多重継承」と「クラス分割」と「オブジェクト指向プログラミング」について勉強したメモ
:published_at: 2017-11-19
:hp-tags: bigen, OOP, Object Orientd Programing, Trait

みなさんこんばんは。*bigen*です。 +
 +
先月、プログラマになって１年経ちましたが、 +
恥ずかしながら先日はじめてPHPのTraitという機能を知りまして、 +
そこから色々勉強したので、とりとめもなくメモしていきます。 +
 +

## 目次
. Traitってどう使うの？ +
. 多重継承のデメリット +
. クラス分割について +
. オブジェクト指向プログラミング（OOP）的な観点では？ +
. おわりに +

## 1. Traitってどう使うの？
PHPにはTraitという水平継承の機能があるそうです。 +
機能の詳細や使い所は下記を参照してください。 +

参考1: http://php.net/manual/ja/language.oop5.traits.php[PHP: トレイト - Manual] +
参考2: http://blog.toshimaru.net/php-trait/[PHP5.4 から導入された trait 機能の使いドコロ - Hack Your Design!] +

ぱっと読んだら実に便利そうなんですが、いくつか疑問点が。 +
 +
①始めから複数クラスを継承できるようにすればいいのでは？ +
②Utilityクラスを水平継承するというやり方は良いやり方なのだろうか？ +
③そもそも継承っていう機能ってなんのためにあんの？ +
 +
これらについて考えました。
 +

## 2. 多重継承のデメリット
**①始めから複数クラスを継承できるようにすればいいのでは？ ** +
 +
Traitは水平継承と書かれていますが、結局のところ複数のクラスを継承できることを意味します。 +
つまり、水平継承ではなく多重継承。 +
PHPは*単一継承しか許さないという縛りがある一方で、同時に多重継承させるような機能を提供する*のは謎です。 +
はじめから多重継承できるようにしとけよって思いました。 +
 +
というわけでなぜ単一継承なのか調べました。 +
 +
参考3:　http://ufcpp.net/study/csharp/oop/oo_multipleinheritance[【雑記】 多重継承できない理由] +
 +
このサイトでは実装上のコストの問題が触れられています。なるほど・・・。 +
こういった多重継承にまつわる問題に対処するため、Mixinという機能もあるそうです。 +
Trait機能に関しても、単純な継承にはないいくつかのルールや制約があるのもそれが理由でしょう。 +
 +
社内で話を聞くと、設計時のリスクについての話題も出てきました。 +
つまり、用心深くクラス設計を行わないといわゆるキメラクラスが作られてしまうということです。 +
これは多重継承だからこそ起きる問題ではないのですが、単一継承のほうが設計が容易でキメラをつくりにくいため安心のようです。 +
 +
他にも、安直な実装をするとクラス間の暗黙の依存関係が生まれやすく、メンテナンス性を損ないやすいなどの問題も指摘されています。 +
 +
そんなこんなで、ただ闇雲に多重継承を使ってしまうと結局デメリットのほうが大きくなってしまうため、実装者のスキルがかなり高くないと使わないほうが良いという意見が多いようです。 +
また、それゆえに多重継承を言語としてそもそも禁止してしまっているものも多く、PHPもその一つのようです。 +

## 3. クラス分割について
**②UtilityクラスをTraitにして水平継承するというやり方は良いやり方なのだろうか？ ** +
 +
ぱっと思いつく水平継承（多重継承）の使い方は、 +
色々なクラスで共通で使うUtilityメソッドをもったクラス（Utilityクラスと呼ぶ）を継承することでしょう。 +
 +
でもUtilityクラスと呼び出し元クラスと依存性が少ないのであれば、メソッドを静的呼び出ししたり、必要であればインスタンス化して使えばいい気がするんですよね。 +
 +
「継承」しなければいけないということは、ポリモーフィズムを期待するということです。 +
これって