# GoのORマッパーを試してみた
:hp-alt-title:　GOlangのORマッパーを試してみた
:hp-tags: NewTsukamoto, mac, Golang, gorm

こんにちは。
エンジニアのNew塚本です。

１０月から歯医者に通い始めて３ヶ月過ちましたが、未だ完治しておりません。 + 
歯を削るキュイーンって音が大の苦手で、苦手というかムリなんです・・・ +
あの音、なんとかならないでしょうかねー +

さて、今回は、初めのGolangとORマッパーのgormを試してみました。


====== 目的
gormライブラリを使って簡単なDB操作を試してみます。 +

ライブラリの詳細は以下のサイトを参照ください。 +
 http://jinzhu.me/gorm/


====== 【DB接続】 +
++++
<pre style="font-family: Menlo, Courier">
import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
)
</pre> 
++++
postgresパッケージは直接は使用されません。gormパッケージからインタフェースを通して使用されます。GOでは、直接使用しないimport文があるとコンパイルエラーとなるため、ブランク修飾子を付けこれを回避します。 +

++++
<pre style="font-family: Menlo, Courier">
func test() {
	// DBコネクション設定
	db, err := gorm.Open("postgres", "user=hoge password=hoge dbname=testdb sslmode=disable")
if err != nil {
		panic(err)
	}
	// DB操作の実処理

	// コネクション解放
	defer db.Close()
}
</pre> 
++++

DBコネクションの設定はこれだけ。 +
db.Close()にdeferキーワードを指定していますが、これは遅延実行を意味します。上記サンプルでは、DBコネクションに失敗した場合にpanic()が発生します。その後、必ず、db.Close()が実行されます。javaのfinally句みたいな感じですね。


====== 【Create編】 +
テーブルとのマッピングはmodelパッケージに、Tb_invoiceという構造体を使用しました。 構造体の名称、メンバ変数の先頭文字が大文字となっているのは、別パッケージから参照可能なpublic変数とするためです。
++++
<pre style="font-family: Menlo, Courier">
package model
type Tb_invoice struct {
	Target_month int
	Client_id int
	Price int
}
</pre> 
++++

++++
<pre style="font-family: Menlo, Courier">
func Create() {
	// DBコネクション設定
	db, err := gorm.Open("postgres", "user=hoge password=hoge dbname=testdb sslmode=disable")
	if err != nil {
		panic(err)
	}

	// DB登録のための構造体
	invoice := model.Tb_invoice{}
	invoice.Target_month = 201711
	invoice.Client_id = 999999
	invoice.Price = 50000
    
	<text style="color:red">db.Create(&invoice)</text>
	
    	// コネクション解放
	defer db.Close()
}
</pre> 
++++

Create関数に登録する情報を設定した構造体のポインタを渡すだけです。

====== 【Read編 Find】 +
++++
<pre style="font-family: Menlo, Courier">
func Find() {
	// DBコネクション設定
	db, err := gorm.Open("postgres", "user=hoge password=hoge dbname=testdb sslmode=disable")
	if err != nil {
		panic(err)
	}

	invoice := []model.Tb_invoice{}

	<text style="color:red">db.Find(&invoice)</text>

	// コネクション解放
	defer db.Close()
}
</pre> 
++++

全件検索するFind関数です。返却値は複数件となるため、構造体配列へのポインタを渡します。

====== 【Read編 Find+Where】 +
++++
<pre style="font-family: Menlo, Courier">
func FindWhere() {
	// DBコネクション設定
	db, err := gorm.Open("postgres", "user=hoge password=hoge dbname=testdb sslmode=disable")
	if err != nil {
		panic(err)
	}
	invoice := []model.Tb_invoice{}
	conditions := model.Tb_invoice{}
	conditions.Target_month = "999999"
    
	<text style="color:red">db.Where(&conditions).Find(&invoice)</text>

	// コネクション解放
	defer db.Close()
}
</pre> 
++++

Find関数に条件を指定することができます。

====== 【Update編】 +
++++
<pre style="font-family: Menlo, Courier">
func Update() {
	// DBコネクション設定
	db, err := gorm.Open("postgres", "user=hoge password=hoge dbname=testdb sslmode=disable")
	if err != nil {
		panic(err)
	}

	invoice := model.Tb_invoice{}

	// 更新データ
	data := invoice
	data.Client_id = 222

	<text style="color:red">db.Model(&invoice).Where("target_month = ?", "999999").Update(&data)</text>

	// コネクション解放
	defer db.Close()
}
</pre> 
++++

Model関数を使います。 +
更新テーブルのインタフェースに対して、更新する値を指定したポインタをUpdate関数に設定するようです。 +
Where関数のインタフェースは、プリペアードステートメント方式でも可能でした。


====== 【その他 Join／Query発行】 +
テーブル結合 +
++++
<pre style="font-family: Menlo, Courier">
joinResult := []model.JoinResult{}

//select項目
col := "a.id, a.hoge, b.color"

//基礎テーブルを指定
db.Table("tableA a").Select(col).

//結合表を指定
Joins("inner join tableB b on (a.id = b.id)").	
Where("a.delete_flag = ?", 0).
Order("a.id asc").
<text style="color:red">Scan(&joinResult)</text>
</pre>
++++
SQL の直書き

++++
<pre style="font-family: Menlo, Courier">
multiResult := []client.MultiResult{}

// 発行するSQL sqlとmodelの変数はキャメルケース
sql := "実行するSQLを記載"
db.Raw(sql).
<text style="color:red">Scan(&multiResult)</text>
</pre>
++++

テーブル結合や、クエリビルダを使用しないSQLもこんな書き方で実行できます。 + 

====== 【その他 トランザクション管理】 +
++++
<pre style="font-family: Menlo, Courier">
// コネクション設定	
db, err := gorm.Open("postgres", "user=hoge password=hoge dbname=testdb sslmode=disable")
if err != nil {
	panic(err)
}

// トランザクション開始
<text style="color:red">mTx := db.Begin()</text>

invoice := model.Tb_invoice{}
invoice.Create_date = time.Now()
	
if err := <text style="color:red">mTx.Create(&invoice).Error</text>; err != nil {
	fmt.Println("err : ", err)
	<text style="color:red">mTx.Rollback()</text>
} else {
	<text style="color:red">mTx.Commit()</text>
}
// トランザクション解放
<text style="color:red">defer mTx.Close()</text>	
</pre>
++++
 
トランザクションを使う場合も簡単に実装できました。 + 

===== 感想
GOのお作法に若干戸惑いましたが、全般的には直感的に書けるので描きやすい言語だと思います。そして、標準ライブラリ（database/sql）との違いですが、標準ライブラリは、Scan関数にマッピングする項目を指定しますが、gormではマッピングする構造体のポインタを渡すだけです。また、db.Debug()にすると、発行するSQLを出力してくれます。
簡単な検証でしたが、これは使えるなと感じました。

おわり
