= 執筆中 Azure Container Service（AKS）で私の人生というコンテナもオーケストレーションしてもらいたい話
:hp-alt-title: Azure 8
:hp-tags: syoga, log, Azure, container, kubernetes, Docker

お久しぶりです、年のせいか風邪がなかなか完治しない自分に若干引き気味な SRE チームの syoga です。

今年も後少しで終わってしまうというこの時期、皆様やり残した事はありますか？

私は Microsoft 社の新型ゲームハード Xbox One X を買いそびれてしまい悶々としております。
日本で売れる訳ないとたかをくくっていたのですが、まさかの転売屋需要により予約が出来ず今にいたっております。

この悔しさを10月に Preview 版がリリースされた Azure Container Service - AKS（以下AKS）へぶつけてみようと思います。

## Azure Container Service とは？
### ACS
以前の Azure Container Service は DC/OS、Docker Swarm、Kubernetes 等の
複数のコンテナオーケストレーションツールが利用できる運用環境に、コンテナを簡単にデプロイできる機能です。

その時の略称は ACS でしたが…

### AKS
今回 Kubernetes に焦点を絞ったサービスに変わったため AKS という略称になりました、Kubernetes の共同制作者の一人 Brendan Burns 氏が現在 Azure のコンテナ関連サービスのトップとなり、バリバリサービスの拡充が進んでいると、先日の Microsoft Connect(); 2017 でもお話がありました。

## 事前準備
・Azure CLI +
ローカルにインストールした Azure CLI で作業しますが、バージョン 2.0.20 以降でないと aks コマンドが利用できませんのでバージョンをご確認下さい。 +
※ Azure Cloud Shell を利用する場合は気にしないで大丈夫です。

・ログイン +
`az login`コマンドで Azure にログインをしておきます。

## 早速やってみる
### リソースグループ作成
Azure ポータルからでも作成できますが、なんとなく CLI を利用し作成してみます、リージョンを eastus としているのは、AKS が日本リージョンでは提供されていないためです。 +
`az group create --name AKSResourceGroup --location eastus` +

### サービスプリンシパル作成
AKS を利用するにはサブスクリプションに紐づく資格情報ではなく、Azure Active Directory のサービスプリンシパルというセキュリティ ID が必要となりますので、以下の通り発行していきます。

```
$ az account set --subscription "サブスクリプション ID"`
$ az ad sp create-for-rbac --role="Contributor" --scopes="/subscriptions/サブスクリプション ID"
{
  "appId": "**********************************",
  "displayName": "azure-cli-2017-11-22-09-39-33",
  "name": "http://azure-cli-2017-11-22-09-39-33",
  "password": "**********************************",
  "tenant": "**********************************"
}
```
利用するのは `appId` と `password` なのでメモメモします。

### AKS 作成
ポータルから AKS を作成します、新規リソースの追加を選び AKS と検索すればすぐに表示されますので、AKS のアイコンを選択してもろもろの情報を入力していきます。

*・基本情報* +
クラスターの名称やリソースグループを入力します、今回は akstest という名称にしました。 +
画像1

*・コンフィグ* +
先程のサービスプリンシパルの情報や、SSH の情報、クラスターのノード数等を入力していきます、今回はノード数を 3 つにします、先程メモメモした `appId` と `password` はここで利用します。

画像2

*・リソースプロバイダの登録検証* +
入力した基本情報、コンフィグ設定でリソースが登録できれば OK ボタンが有効化されます。

画像3

OK ボタンを押せば AKS の作成は完了です。

## kubernetes クラスタへデプロイ
今回利用する Docker コンテナイメージを保持しておくため Azure Container Registory（以下ACR）に AKStestblog というリポジトリを作成しておきました。

### ACR へコンテナイメージを Push
ここからは CLI で作業します、まずは `az acr login --name AKStestblog` でACRにログインします。

利用するイメージは Microsoft がサンプルで提供している投票システムとなり、Redis のコンテナと Python で作成された Web アプリケーションのコンテナ、 2 つのコンテナで動作しています。

上記イメージにタグを付与し、ACR に Push します。 +
```
docker tag azure-vote-front xxxxxxxx.azurecr.io/azure-vote-front:akstest
docker push xxxxxxxx.azurecr.io/azure-vote-front:akstest
```

### そしてデプロイ！！
忘れちゃいけない！ kubectl CLI のインストールが必要ですので Azure CLI 経由でインストールするため `az aks install-cli` を実行します。 +
※ Azure Cloud Shell を利用する場合は気にしないで大丈夫です

以下コマンドで作成した AKS へ接続します。 +
`az aks get-credentials --resource-group=AKSResourceGroup --name=akstest`

ここからは kubectl CLI を使っていきます、まずはノードを確認します。
```
$ kubectl get nodes
NAME                       STATUS    ROLES     AGE       VERSION
aks-agentpool-42554519-0   Ready     agent     17h       v1.8.1
aks-agentpool-42554519-1   Ready     agent     17h       v1.8.1
aks-agentpool-42554519-2   Ready     agent     17h       v1.8.1
```
AKS 作成時に設定した通り3 ノード立ち上がっています。

### マニフェストファイル更新
Kubernetes はデプロイ時にマニフェストファイル

アプリケーションをデプロイする
INV-454:docker s290$ kubectl create -f azure-vote-all-in-one-redis.yml
deployment "azure-vote-back" created
service "azure-vote-back" created
deployment "azure-vote-front" created
service "azure-vote-front" created

作成の中確認
kubectl get service azure-vote-front --watch

NAME               TYPE           CLUSTER-IP   EXTERNAL-IP   PORT(S)        AGE
azure-vote-front   LoadBalancer   10.0.76.67   <pending>     80:32233/TCP   37s

kubectl get service azure-vote-front
NAME               TYPE           CLUSTER-IP   EXTERNAL-IP      PORT(S)        AGE
azure-vote-front   LoadBalancer   10.0.76.67   52.170.117.231   80:32233/TCP   7m

すけーるするぞ
kubectl get pod -o wide
NAME                               READY     STATUS    RESTARTS   AGE       IP           NODE
azure-vote-back-7556ff9578-7pxp9   1/1       Running   0          14m       10.244.0.4   aks-agentpool-42554519-2
azure-vote-front-f4759f4b7-l4vgc   1/1       Running   0          14m       10.244.1.4   aks-agentpool-42554519-1

kubectl scale --replicas=8 deployment/azure-vote-front

get pod -o wide
NAME                               READY     STATUS              RESTARTS   AGE       IP           NODE
azure-vote-back-7556ff9578-7pxp9   1/1       Running             0          19m       10.244.0.4   aks-agentpool-42554519-2
azure-vote-front-f4759f4b7-55p24   0/1       ContainerCreating   0          6s        <none>       aks-agentpool-42554519-2
azure-vote-front-f4759f4b7-8dvcw   0/1       ContainerCreating   0          6s        <none>       aks-agentpool-42554519-2
azure-vote-front-f4759f4b7-l4vgc   1/1       Running             0          19m       10.244.1.4   aks-agentpool-42554519-1
azure-vote-front-f4759f4b7-mbvsv   0/1       ContainerCreating   0          6s        <none>       aks-agentpool-42554519-0
azure-vote-front-f4759f4b7-ms9pz   0/1       ContainerCreating   0          6s        <none>       aks-agentpool-42554519-0
azure-vote-front-f4759f4b7-rvb8l   1/1       Running             0          6s        10.244.1.5   aks-agentpool-42554519-1
azure-vote-front-f4759f4b7-tczrj   0/1       ContainerCreating   0          6s        <none>       aks-agentpool-42554519-0
azure-vote-front-f4759f4b7-vclzg   0/1       ContainerCreating   0          6s        <none>       aks-agentpool-42554519-2

INV-454:docker s290$ kubectl get pod -o wide
NAME                               READY     STATUS    RESTARTS   AGE       IP           NODE
azure-vote-back-7556ff9578-7pxp9   1/1       Running   0          20m       10.244.0.4   aks-agentpool-42554519-2
azure-vote-front-f4759f4b7-55p24   1/1       Running   0          1m        10.244.0.6   aks-agentpool-42554519-2
azure-vote-front-f4759f4b7-8dvcw   1/1       Running   0          1m        10.244.0.5   aks-agentpool-42554519-2
azure-vote-front-f4759f4b7-l4vgc   1/1       Running   0          20m       10.244.1.4   aks-agentpool-42554519-1
azure-vote-front-f4759f4b7-mbvsv   1/1       Running   0          1m        10.244.2.5   aks-agentpool-42554519-0
azure-vote-front-f4759f4b7-ms9pz   1/1       Running   0          1m        10.244.2.4   aks-agentpool-42554519-0
azure-vote-front-f4759f4b7-rvb8l   1/1       Running   0          1m        10.244.1.5   aks-agentpool-42554519-1
azure-vote-front-f4759f4b7-tczrj   1/1       Running   0          1m        10.244.2.6   aks-agentpool-42554519-0
azure-vote-front-f4759f4b7-vclzg   1/1       Running   0          1m        10.244.0.7   aks-agentpool-42554519-2

#### 感想
お気軽に Kubernetes 環境へデプロイができるという点は素敵なのではないでしょうか

完