# システム開発で使われるドキュメントについて考えてみる
:hp-alt-title:　システム開発で必要なドキュメントについて考えてみる
:hp-tags: NewTsukamoto

こんにちは。
エンジニアのNew塚本です。

私、今年が本厄でして、去年からロクなことが起きておりません。 +
車検をあげた次の月にヘッドライトが切れ、次の月になんと高速でタイヤがバースト、 +
さらに、上野の件や、車をぶつけられたり。 +
まだまだありますが・・・ホンキでお祓いを考えてます。

気を取り直して！ +
今回は、システム開発におけるのドキュメントについて考えてみました。


====== きっかけ

私は長年、ウォーターフォールモデルでの開発をしていました。 +
上流から下流へ水が流れる様に工程を・・・っていう、あれです。 +

更に、開発標準なるフォーマットがあり、それに則って、各工程での成果物（ドキュメント類）が決められてました。 
（正直これいる？みたいなやつもありますが・・・。）

アジャイル開発も経験してますが、 +
そこは極端でしたので一切ドキュメントは書きませんでした。

ドキュメント（設計書）って、誰の為に何で必要なのか。 +

そんなモヤっとした感じを、今回考えてみました。


====== まず・・・

私の経験から、システム開発でお目にかかるドキュメントは、大まかにはこんなものがありました。

・要求仕様書 +
クライアントが開発を請け負う人に対し、開発を依頼するシステムの要件を文章化したものです。
大体、５W1H(目的、予算、納期、運用)で記載されている事が一般的です。

・要件定義書 +
システム開発側から要求仕様に対する実現性を纏めた資料

・基本設計書 +
システム化に向けて大まかに纏めた設計書
　
・詳細設計書 +
基本設計で定義した機能を、フローや入出力等を纏めた設計書

・プログラム設計書 +
プログラムをどの様に実装するかを書いた設計書

・テスト仕様書 +
試験観点、テスト項目、バグ検出密度などを纏めた設計書


====== それぞれ何の為に必要か？
設計工程でのドキュメント（要件定義、基本設計、詳細設計）について考えてみます。


・要件定義書 +
抽象的な要求仕様をシステム化するのですから、認識ずれを起こさない様にやる事、やり方などを決めておく必要があります。 詰め切れない内容は申し送り事項として、抜け漏れを起こさない事が必要です。重要な点はクライアントの視点で記載する事だと思います。

++++
<pre style="font-family: Menlo, Courier">
・クライアントと開発者が、システム全体像を共有をするために必要
・やる事を明確にする事が必要
</pre>
++++


・基本設計書 +
システム化に向け、抽象的だった要件をより具体的に落とし込む必要があります。 +
また、画面が必要であればレイアウトや動作についても決めておく必要があります。このあたりから、開発者の視点で記載する事が増えてくると思います。

++++
<pre style="font-family: Menlo, Courier">
・クライアントと開発者が、具体的な要件を共有をする為に必要
・大まかな挙動はすり合わせ確定させておく
</pre>
++++


・詳細設計書 +
基本設計から更に詳細化しますが、今度は開発者の視点で記載されていきます。
処理フロー定義や、エンティティの物理設計などをするかと思います。

++++
<pre style="font-family: Menlo, Courier">
開発者がプログラムを作る設計図として必要
</pre>
++++


====== 思い返してみると・・・
クライアントと基本設計のレビューをした際に、
何だか「？？？」みたいな反応になった経験はありません？
私はありました。

要件定義では、「そうだね！」みたいな反応が、機能定義など踏み込んだ話になると「・・・・・うん。」みたいな微妙な反応。

レビューのスキルもあるかと思いますが、

これ、考えてみました。 +

開発者の視点で内容がどんどん追加されていくと、
クライアントの視点からはどんどん離れて行くんですよね。
いわゆるギャップです。


===== 感想
当たり前な話ですが、何のために必要なのかを意識する事って重要ですね。ドキュメントはこの意識が大切だと再認識しました。但しですが、詳細設計書とかプログラム設計書ってメンテナンス大変じゃないですか。プログラムと一致している必要があるのですが、追加開発やバグ修正などで、プログラムはどんどん変更されていき、この部類の設計書はおざなりになり易く、ずれてくるんですよね。


おわり
