= バーチャル空間LTとスライドオンリーLTを比べてみた
:hp-alt-title: vr_lt
:hp-tags: obata, vr, Virtual Cast, LT

## ボーナスの使いみちはVRでした
あっという間に7月です。 +
新卒2年目エンジニアの小畑です。

新卒2年目の私が今この時期にいる、つまり、ボーナスが美味しい！

ってことで、がっつり大きな買い物しました。

ハイスペックPCとOculus RiftというVR(バーチャルリアリティ:仮想空間でいろいろする)の機材であるHMD(ヘッドマウントディスプレイ:ゴーグルのように頭にかけるディスプレイ)を買いました。 +
組み立てたとはいえ、25万くらい消えたのは気の所為。

実は学生時代にOculus Riftの製品版の前の開発者版を使ったことはあったのですが、 +
そのときの感動が忘れられなく、とうとう社会人になって製品版買っちゃいました。

で、今や社会人な私は、VRを手に入れて何がしたいって、遊ぶのより、面白い使い方をすることを考える方が楽しいのです。

そこでエンジニアといえば・・・で考えました。

そうだ、LT+VRだ。

### LTとは
ライトニングトークの略で、短時間でプレゼンテーションをすることです。

## 何をしたか
普通にスライドと音声を録画するものと、 +
バーチャル空間でプレゼンをしたものを録画するのと、 +
どんな違いがあるだろう？と比較してみました。

### 普通のスライドでプレゼン
百聞は一見にしかず

ということで、軽いプレゼン用意しました。


+++
<iframe width="560" height="315" src="https://www.youtube.com/embed/SsaCbXNyCvU" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
+++

### バーチャル空間でプレゼン
こちらも用意しました。

+++
<iframe width="560" height="315" src="https://www.youtube.com/embed/eMt3lmPnPcY" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
+++


## 違いまとめ
■普通のスライド +
余計な情報ない、シンプル

■バーチャル空間 +
ボディーランゲージ使える +
文字の見にくさ・スライドに集中できない行動には気をつける必要がある

表現力という点では、バーチャル空間の方が良いと思います！ +
気をつけるところを気をつけることが重要だと思います。



## おまけ:でもやるの大変なんでしょ？
バーチャル空間でのプレゼンは非常に簡単にできました。

無料で提供されているサービス『Virtual Cast』を使用させていただきました。

■Virtual Cast +
https://virtualcast.jp/


■やったこと +
・Googleスライドつくる +
・画像化する +
・画像をネットに公開する +
・設定ファイルにURLを書く +
・画面写してしゃべるだけ +

詳細なやり方に関しては、今回の内容とは逸れるので、  
知りたい人が多かったら記事にしようと思います。

とりあえず、興味を持ったみなさん、次のボーナスはPCとHMDに投資しましょう！！！