= 執筆中。とりあえずコピー
:hp-tags: sumomo, Laravel, Request, beginner


こんにちは、未経験中途エンジニアの、すももです。 +
今回は、業務で使用しているLaravelのリクエストクラスについて、手の長いリーダーから色々教えてもらったので、Laravel初心者向けに書きたいと思います〜。 +
 +
 +
 
 
## リクエストURIなどの取得 +

=== 〜準備〜

▪️routes/web.php

```
Route::get('/test/{a}/{b}', 'TestController@test');

```

▪️app/Http/Controllers/TestController.php

```
public function test(Request $request)
{
    dd(
        // リクエストURIの取得
        $request->path(),
        // リクエストのURIが指定されたパターンに合致するか確認
        $request->is('*/sumo'),
        // 完全なURLを取得(クエリ文字列なし)
        $request->url(),
        // 完全なURLを取得(クエリ文字列付き)
        $request->fullUrl(),
        // リクエストメソッドの取得
        $request->isMethod('post')
    );
    return view('test.index');
}

```

試しに、`例：http://localhost/test/lala/sumo?aaa=bbb`にアクセスしてみる。 +
※（）内が取得した内容です↓ +


```
【pathメソッド】
// リクエストURIの取得→（test/lala/sumo）
$request->path();
```
【pathメソッド】では、クエリ文字列はなしの`http://localhost/`以降が取得できました。 +


```
【isメソッド】
// リクエストのURIが指定されたパターンに一致するか判定→（true）
$request->is('*/sumo');
```
【isメソッド】では、`true/false`が返ってきます。 +
今回はURIの最後が`/sumo`で一致している為`true`です。（*をワイルドカードとして使用できます。） +


```
【urlメソッド】
// 完全なURLを取得(クエリ文字列なし)→（http://localhost/test/lala/sumo）
$request->url();

【fullUrlメソッド】
// 完全なURLを取得(クエリ文字列付き)→（http://localhost/test/lala/sumo?aaa=bbb）
$request->fullUrl();
```
【urlメソッド】【fullUrlメソッド】では、クエリ文字列有り無しのURLが取得できました。 +
用途によって使い分けられそうですね。 +


```
【methodメソッド】
// リクエストメソッドの取得→（GET）
$request->method();

【isMethodメソッド】
// リクエストメソッドの判定→（false）
$request->isMethod('post');
```
【methodメソッド】では、リクエストのHTTP動詞が取得できます。 +
【isMethodメソッド】の方は、 指定した文字列とHTTP動詞が一致するか`true/false`で判定してくれます。 +
使いどころはいまいち分からないのですが、「めそっどめそっど」ってくどい名前が気に入ったので紹介してみました。
 +
 +
 
・・・そもそも`$request`で取れるのは、フォームとかから送ったデータだけかと思ってました。笑 +
GETリクエストの時も、いろいろ取得できるのですね〜 +
 +
 +


## フォームで入力したデータを受け取る +

=== 〜準備〜

▪️routes/web.php

```
Route::post('/testregist/{a}/{b}', 'TestController@testregist');
```

▪️resources/views/test/index.blade.php

```
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>リクエストの勉強</title>
</head>
<body>
    <h1>入力フォーム</h1>
    <div>
        {{ Form::open(['url' => '/testregist/lala/sumo', 'method' => 'post']) }}
            <label>お名前：<input type="text" name="name"></label><br>
            <label>メール：<input type="text" name="mail"></label><br>
            <label>パスワード：<input type="password" name="password"></label><br>
            <input type="submit" name="regist" value="送信する">
        {{ Form::close() }}
    </div>
</body>
</html>
```


▪️app/Http/Controllers/TestController.php

```
public function testregist(Request $request)
{
    dd(
        // 名前の取得
        $request->input('name'),
        // リクエストにnameが存在していない場合に、デフォルト値で指定したsumoを返す
        $request->input('name', 'sumo'),
        // リクエストの全入力データを配列で取得
        $request->all(),
        // リクエストからnameの入力データだけ取得
        $request->only('name'),
        // リクエストからpassword以外の入力データを取得
        $request->except('password'),
        // リクエストにnameが存在するか判定
        $request->has('name'),
        // リクエストにnameが存在しており、かつ空でない事を判定
        $request->filled('name')
    );
    return view('test.index');
}
```
簡単に、名前・メールアドレス・パスワードを送信するフォームを作成しました。 +
試しに以下内容を送ってみます。
```
お名前：すもも
メール：sumo@xxx.jp
パスワード：abcdefg
```
※`☓☓☓`の箇所には、bladeで設定した`input type`の`name="☓☓☓"`より取得したいデータの名前を入れてください。 +


```
【inputメソッド】
// ☓☓☓の取得
$request->input('☓☓☓');
例：$request->input('name');→（すもも）

```
【inputメソッド】では、指定した項目のデータが取得できました。 +
`input`を省いて`$request->name;`でも同様に指定データを取得できます。


```
【inputメソッド〜デフォルト値指定〜】
// リクエストに☓☓☓が存在していない場合に、デフォルト値で指定した△△△を返す
$request->input('☓☓☓', '△△△');
```
【inputメソッド〜デフォルト値指定〜】は、フォームに該当の項目`name="☓☓☓"`があるけどユーザーが未入力だった場合ではなく、そもそもフォームに指定した`name="☓☓☓"`が存在しない時にデフォルト値が返ってきます。 +


```
【allメソッド】
// リクエストの全入力データを配列で取得
$request->all();

【onlyメソッド】
// リクエストから☓☓☓の入力データだけ取得
$request->only('☓☓☓');

【exceptメソッド】
// リクエストから☓☓☓以外の入力データを取得
$request->except('☓☓☓');
```
【allメソッド】は全入力データ、【onlyメソッド】は指定データだけ、【exceptメソッド】は指定データ以外を取得できます。 +
`only`や`except`は、パスワードなどの機密情報を含めたくない時などに良さそうですね。



```
【hasメソッド】
// リクエストに☓☓☓が存在するか判定→（）
$request->has('☓☓☓');

【filledメソッド】
// リクエストに☓☓☓が存在しており、かつ空でない事を判定→（）
$request->filled('☓☓☓');

```


## 番外編（ヘルパ関数） +

```
// →（）
dd($☓☓☓);

// →（）
dump($☓☓☓);

```

```
// →（）
snake_case();

// →（）
camel_case();

// →（）
snake_case();

// →（）
studly_case();

// →（）
title_case();

// →（）
kebab_case();

```






## 感想 +

ああああああ +
 +
〜おしまい〜 +


