= ECRにイメージを置いてみよう
:hp-alt-title: try_ecr
:hp-tags: obata, docker, aws, ecr

## JAWS DAYSで刺激を受けてしまった

JAWS DAYS 2018楽しかったですね。

AWSを殆ど使ったことのない初心者な私でも、お話はどれも興味深くて、 +
行ってよかったと思えるイベントでした。

やはりfargateはあちこちで早速使われている様子でしたね。

まあこんな感じにイベント行って刺激を受けてしまったら・・・まあ使ってみるしかないよね！

ってことで、とりあえず最初の一歩ということでECRにイメージを置いてみるところから始めてみました。

（決して、ECSまでやろうとしたのに、タイムアップになったとかそんなではないですからね！！！嘘ですすみません、ハマりまくって間に合いませんでした）


## 手順

■事前準備

1. ユーザー・ユーザーグループを作成する(IAM)
2. AWSCLIをいれる（コマンドラインインターフェース）

■本命

1. AWSでリポジトリを作成する
2. Dockerfileからイメージをビルドする
3. イメージにアップロード先のタグを付ける
4. イメージをプッシュする

事前準備で超手間取った・・・今までAWS使っていなかったから・・・

2.AWSCLIは、Macの方なら`brew install awscli`で1コマンドで十分です。

とりあえず、この記事では本命の手順を説明いたします。


## 1. AWSでリポジトリを作成する

1. AWSにログイン
2. 検索窓に『ECS』と打つ
3. Amazon ECSの画面に来たら、画面左のAmazon ECSの下、リポジトリを選択する
4. リポジトリの作成を選ぶ

で、とりあえず作成画面にいけます！

あとは、

リポジトリ名を入れたら

[imageタグあとで入れる]

できたー！！！

[imageタグあとで入れる]

あとは、ページの説明に従ってやればおしまいですが・・・一応説明していきます！

## 2. Dockerfileからイメージをビルドする

とりあえず、Dockerfileを書きます。

```
FROM php:7.2-fpm

RUN apt-get update \
 && apt-get install -y \
    git \
    zip \
    unzip \
    vim \
    iputils-ping \
    net-tools
    
COPY ./ /var/www

WORKDIR /var/www
```

で、`docker build --tag my_image_php-fpm .`とかでイメージを作っておきましょう


## 3. イメージにアップロード先のタグを付ける
さっき作ったイメージがあると思うので、
`docker tag my_image_php-fpm:latest ◯◯◯/my_first_php-fpm:latest`
って打っていきましょう。

`docker images`で、新しくタグ付けされたイメージが見つかると思います。

## 4. イメージをプッシュする
`docker push ◯◯◯/my_first_php-fpm:latest`でイメージをプッシュしちゃいましょう！

ソースの大きさによっては少し時間かかっちゃうかもしれません。

それが完了したらおしまいです！

AWSのECRのページに行けば、イメージファイルの大きさが表示されてると思います。

おつかれさまでした！

# 感想
AWS、初期設定さえすればサックサク。 +
ECSにこんなにハマると思ってなかった。 +

ECRは思った以上に簡単でした！初期設定が出来ている人は、一瞬で使えます。

ECSはリベンジしたいところ。

少しずつAWSに慣れようと思います！では、また50日後くらいに会いましょう！