= [和訳] ホラクラシー憲法 v.4.1〜第1章
:published_at:
:hp-tags: bigen, holacracy, holacracy constitution, translation, japanese


どうも、*bigen*です。 +
最近マネジメントの勉強をいろいろしていまして、イマドキっぽいホラクラシーという組織体系について勉強しています。 +
ちなみに今はこちらの本を読んでいます。 +

-- https://www.amazon.co.jp/dp/4569827713[HOLACRACY 役職をなくし生産性を上げるまったく新しい組織マネジメント]

その中で、再三ホラクラシー憲法というワードが出てきてます。 +
非常に重要そうなのですが、書籍内では出てこなかったのでWebを探した所、原文はこちらで読めることがわかりました。 +
https://www.holacracy.org/resources/

ただし日本語がない！ +
色々探してみたんですが、きちんと日本語訳されたものが見当たらなかったので、 +
せっかくなので和訳してみます。 +

これがなかなか日本語で表現するのが難しい内容でして、今回は第1章までで力尽きましたが、 +
ある程度量が溜まってきたらまとめて見られるようにしようと思います。 +

ではどうぞ

== 前文
この*憲法*は、組織の運営と活動のプロセス及びルールを定義するものである。 +
これを*批准する者*は、この憲法を導入する*組織*の権限構造としてこれらのルールを正式に採択することになる。 そしてその組織は、批准する者によって統治し動かしていくことのできるものとなる。 +
これを批准する者、及び憲法が導入された組織の運営と活動の一部を担うことに同意するもの（パートナーと呼ぶ）は、憲法によって与えられる権限に疑念を抱くことなく信頼し、その義務と制約を快く受け入れられるようになるだろう。 +

[quote]
----
PREAMBLE
This “Constitution” defines rules and processes for the governance and operations of an organization. 
The “Ratifiers” are adopting these rules as the formal authority structure for the “Organization” specified upon the Constitution’s adoption, 
which may be an entire entity or a part of one that the Ratifiers have authority to govern and run. 
The Ratifiers and anyone else who agrees to take part in the governance and operations of the Organization (its “Partners”) 
may rely upon the authorities granted by this Constitution, and also agree to be bound by its duties and constraints.
----

== 1 組織に活力を与える"役割"
=== 1.1 役割の定義
パートナーは原則として、明示的に定義された*役割*のもとで組織に貢献することになる。 +
*役割*とは、役割の名前と下記のうち最低１つ以上のものを合わせて明文化したもので定義される。 +

*(a) 1つの目的* ： 限界一杯の、またはなんとか達成できそうな、あるいは達成不可能な目標で、組織の利益ためにこの役割が追求、あるいは具現化していくもの。 +
*(b) 1つ以上の領域* : 組織の利益のために制御するものごとで、他の役割から制限を受けず独占的にコントロールすべきもの。 +
*(c) 1つ以上の責務* :  この役割に期待されている現在進行系の活動で、組織内の他の役割に貢献するか、またはこの役割自身の目的達成に貢献する活動。 +

[quote]
----
ARTICLE I
ENERGIZING ROLES

1.1 DEFINITION OF A ROLE
The Organization’s Partners will typically perform work for the Organizationby acting in an explicitly defined Role. 
A “Role” is an organizational construct with a descriptive name and one or more of the following:
(a) a “Purpose”, which is a capacity, potential, or unrealizable goal that the Role will pursue or express on behalf of the Organization.
(b) one or more “Domains”, which are things the Role may exclusively control and regulate as its property, on behalf of the Organization.
(c) one or more “Accountabilities”, which are ongoing activities of the Organization that the Role will enact.
----



=== 1.2 役割に伴う責任

組織のすべてのパートナーは、役割が割り当てられ、その役割を果たすことに同意した場合には、以下の責任を果たさなければいけない。 +

==== 1.2.1 歪みへの対処
自分の役割に与えられた目的や責務がどのように表現されて定義されているかに常に気を配り、 あなたが考えうる理想的な表現と比較することに責任を持つ。 +
これは、今の現実と、あなたが感じ取る可能性とのギャップを特定するためである（このギャップを"歪み"と呼ぶ）。 +
また、役割に与えられた権限の中で、あるいはこの憲法のもとに認められたプロセスを利用して、それらの歪みの解消へ向けて行動することに責任を持つ。 +

==== 1.2.2 目的と責務の遂行
自分の役割に与えられた目的と責務をいかに果たしていくかについて常に考え続けること、およびその過程として以下を定めることに責任を持つ。 +

*(a) 次のアクション* : 直ちに実行可能であり、少なくとも他に優先すべきものが現れるまでは直ちに実行したほうが有益と考えられる行動。 +
*(b) プロジェクト* : 複数の一連の活動を必要とする成果物で、 少なくとも他に優先すべきものが現れるまではそこへ向けて活動したほうが有益だと考えられるもの。

==== 1.2.3 プロジェクトの推進
進行中の全てのプロジェクトに対して、いかにして完了させるかについて考え続けることに責任を持つ。 +
これは、プロジェクトを前進させる為の有用な次のアクションが一つも定められていない場合であっても例外ではない。 

==== 1.2.4 プロジェクト、次のアクション、歪みの監視
全てのプロジェクトおよび次のアクションに対して、データベースやそれに準じる形で常にデータを収集し計測することに
責任を持つ。 +
また、そのデータベースが進行中あるいはこれから取り掛かる仕事を常に反映している状態を維持するために、定期的にデータベースをチェックし更新することに責任をもつ。 +

==== 1.2.5 意識とリソースを割くこと
その役割のために割ける時間があるかぎり、その時がくれば効率的かつ効果的に実行できるであろう"次のアクション"を模索し続けることに責任を持つ。 +
また、組織の一員として一番価値を生み出せると思える行動は全て実行に移すことに責任を持つ。


[quote]
----
As a Partner of the Organization, you have the following responsibilities for
each Role that you are assigned to and agree to fill:
1.2.1 PROCESSING TENSIONS
You are responsible for monitoring how your Role’s Purpose and
Accountabilities are expressed, and comparing that to your vision of their
ideal potential expression, to identify gaps between the current reality and
a potential you sense (each gap is a “Tension”). You are also responsible
for trying to resolve those Tensions by using the authorities and other
mechanisms available to you under this Constitution.
1.2.2 PROCESSING PURPOSE & ACCOUNTABILITIES
You are responsible for regularly considering how to enact your Role’s
Purpose and each of your Role’s Accountabilities, by defining:
(a) “Next-Actions”, which are actions you could execute immediately and
that would be useful to execute immediately, at least in the absence of
competing priorities; and
(b) “Projects”, which are specific outcomes that require multiple
sequential actions to achieve and that would be useful to work towards, at
least in the absence of competing priorities.
1.2.3 PROCESSING PROJECTS
You are responsible for regularly considering how to complete each
Project you are actively working towards for your Role, including by
defining any Next-Actions useful to move the Project forward.
1.2.4 TRACKING PROJECTS, NEXT-ACTIONS, & TENSIONS
You are responsible for capturing and tracking all Projects and NextActions
for your Role in a database or similar tangible form, and for
regularly reviewing and updating that database to maintain it as a trusted
list of the Role’s active and potential work. You are also responsible for
tracking any Tensions you identify for your Role, at least until you process
them into desired Projects or Next-Actions, or otherwise resolve them.
1.2.5 DIRECTING ATTENTION & RESOURCES
Whenever you have time available to act in your Role, you are responsible
for considering the potential Next-Actions you could efficiently and
effectively do at that point in time, and executing whichever you believe
would add the most value to the Organization from among that subset.
----


=== 1.3 実行権限
パートナーに役割が割り当てられると、役割の目的と責務を果たすために有益だと合理的に考えられる全ての"次のアクション"を実行する権限が与えられる。 +
ただし、別の役割（または同様の権利を有するもの）に割り当てられた領域にあるものに対して、その役割の許可なく制御したり重大な影響を与えたりしてはいけない。 +
ここに書かれた実行権限については、2.1.3で更に詳細に規定される。


[quote]
----
1.3 AUTHORITY TO ACT
As a Partner assigned to a Role, you have the authority to execute any NextActions
you reasonably believe are useful for enacting your Role’s Purpose or
Accountabilities.
However, you cannot exert control or cause a material impact within a
Domain owned by another Role or another sovereign entity, unless you have
their permission. The authority granted in this paragraph is further limited by
Section 2.1.3.
----

=== 1.4 領域内での権限
パートナーに役割が割り当てられると、役割の全ての領域内の制御と調整の権限が与えられる。 +
他社から自分の担当領域内のモノを制御したり影響を与えたりする許可を求められた時は、その時々の判断で許可しても断ってもよい。 +
あるいは、自分の領域に対して"ポリシー"を定義することもできる。これは、領域内で他者が制御や影響を加えること権限を与えたり、逆に他で与えられた権限を制限したりするものである。 +
なお、ポリシーは影響を与えうるパートナー全員がアクセスできる場所で公開されるまで有効にはならない。 +
ここで書かれた領域内での権限については、2.1.3以下で更に詳細に規定される。


[quote]
----
1.4 AUTHORITY OVER DOMAINS
As a Partner assigned to a Role, you have the authority to control and regulate each Domain of your Role. You may do this on a case-by-case basis when others request permission to impact one of your Domains, by considering the request and allowing or withholding permission.
You may also define “Policies” for your Domains, which are either grants of authority that allow others to control or cause a material impact within
a Domain, or limits on how others may do so when otherwise authorized. Before a Policy is valid, you must first publish it in a forum convenient to all Partners who may be impacted.
The authorities granted to you in this section may be further limited by constraints defined under Section 2.1.3.
----