# LaravelとNexmoでSMSの配信をしてみた
:hp-alt-title:  LaravelとNexmoでSMSの配信をしてみた
:hp-tags: Laravel, Nexmo, AhYung, SMS

Hello~~アヤンです

最近Laravelのメール配信の機能を触ることが多くて、SMSで同じようなことを試して見ました。
また、先週サンクスギビングデーというアメリカの祝日があって、料理をする機会がありました〜

その日のため、様々な料理を作りたくて、気づいたらタブを２０個以上開いてありました...
どの料理がどの調理時間をほぼ忘れてしまって、間違えたらパンを肉の焼く時間にして焦げてしまいました（泣）
それを避けるためこれを考えました！


#### 目的
レシピサイトでタイマーを押すと調理時間が終わったらユーザーの携帯に携帯メールが飛んでくる 

#### 使ったツール
Laravel 5.7
Nexmo (別のアカウント登録が必要）


###### 1. 環境構築
composerでPHPClientLibraryをインストールする
----
composer require nexmo/client
----

config.appのファイルのProvidersにNexmoServiceProviderを追加
----
    'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
	//他のProviders
        Illuminate\View\ViewServiceProvider::class,
       //NexmoのProvider
        Nexmo\Laravel\NexmoServiceProvider::class,
----
 
次は.envファイルにNexmoのアカウント情報の追加→Nexmoからコピーペースト
----
NEXMO_KEY= Nexmoのアカウントページに書いてあるAPI Key（「(Master)」なし
NEXMO_SECRET= Nexmoのアカウントページに書いてあるAPI secret
----

それで環境構築完成！
 	希望があればconfig/app.phpファイルにAlliasを設定ができます

##### 2. SMS用のコントローラー作成
php artisanでコントローラークラスを作成しましょう
----
php artisan make:controller SMSController
----

Nexmoのクラスを使いたいのでnamespaceの下にNexmoのFacadeを追加
----
<?php

namespace App\Http\Controllers;

//↓
use Nexmo\Laravel\Facade\Nexmo;
use Illuminate\Http\Request;
----

次はメッセージの内容と送る先に関数で指定しましょう
----
    public function sendFinishedCookingSMS()
    {
        Nexmo::message()->send([
            'to' => '',
            'from' => 'Fooood Time',
            'text' => 'ビーフシチュー出来上がりました！'
            'type' => 'unicode'
        ]);
    }
----
テストのため、送る先の'to'のところでNexmoに登録されている携帯番号を追加しました。

送る側の方でお好きな値を入れても構わないのですが、携帯の画面で数字になります。

'text'のところでメッセージ内容を書きます。

##### 3. Vueとコントローラーのルーティングを設定する
web.phpのファイルでget('好きなURL', 'コントローラー名@関数名')のように指定します。
----
Route::get('/sms/send', 'SMSController@sendFinishedCookingSMS');
----

##### 4. 最後にVue側から呼び出す
----
        sendFinishSms() {
            axios
                .get('/sms/send')
                .then(response => {
                    this.textResult = 'Text notification was sent!'
                }).catch(error => {
                    this.textResult = 'Error in sending text notification'
                });
        }
----

今回作ってみたページに関してはページに表示されているタイマーが終わったら、SMSを送る関数を呼ぶ出すようにしています。
携帯の画面はこちらです




##### Pass By Reference


###### References
- https://javascript.info/class
- https://www.w3schools.com/Js/js_function_parameters.asp
- https://www.digitalocean.com/community/tutorials/understanding-classes-in-javascript#defining-methods
- https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Basics#Object_basics
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Details_of_the_Object_Model
- https://codeburst.io/javascript-pass-by-value-and-pass-by-reference-in-javascript-fcf10305aa9c
- https://abdulapopoola.com/2013/03/30/static-and-instance-methods-in-javascript/


Done
