= VR空間のスクショで漫画や画像素材作成をする
:hp-alt-title: vr_comic
:hp-tags: obata, vr, Virtual Cast, comic

## VRが生活の一部になってます
あっという間に9月です。 +
新卒2年目エンジニアの小畑です。

ってことで、もう前回のブログから2ヶ月経つんですね。 +
生活の中にVRが入ってもう2ヶ月経つとも言います。はっや・・・

某カオスななんとかチャットで、また交友の幅が広がったりしてました。 +
知り合った人がWeb系エンジニアで、技術力高い人とかはむしろしょっちゅうあるくらいでした。 +
いやー時代が変わってきてるのを感じます。

さてさて、前回のブログで、ボディーランゲージがわりと大切なのかなってお話に触れました。 +
今回は、ボディーランゲージを大切にしながら、3次元から、さらに次元を下げた挑戦してみました。

## こうしました
漫画での説明、わかりやすいな。 +
私にも作れないかな。

そうだ、VRだ!(???)


もはやVR関係なくなってますね。 +
VRってなんだ・・・

## やったこと
1. VirtualCastつかってスクリーンショットを取る
2. Googleスライドで加工する
3. 画像で出力する

おしまい。

■Virtual Cast +
https://virtualcast.jp/

## 所要時間
10分いらないくらい

## 何が嬉しいの？
### 1.簡単に画像素材が作成できる！

○○な構図の素材が見つからない・・・そんなときに、オリジナル素材が簡単に作れちゃう！

### 2.匿名性が保たれる！

人でやると、個人が特定されてしまいますが、 +
これなら個人の特定はされません！

### 3.ありえない構図も可能

Virtual Castではない、他の環境でスクリーンショットを取れば、 +
空を飛ぶとか、魔法を放つとか、銃とかを、合成頼らずに出来ます！ +
ある意味、これ全部が合成とも言えますが！

■吹き出しとか作れば、インパクトの大きい記事が出来上がり！ +
この記事も最初のインパクトは大きかったと思います！


## 難点
### 1.狙った構図は慣れが必要

いわゆる、素材屋さんの素材は、慣れてる人が作成したものです。 +
最初の内は目立った表現力の差が出るのは避けられないです。

### 2.複数人出すには、仲間か画像合成が必要

ぼっちには辛いです。 +
画像合成に関しては、グリーンバックとかでスクリーンショットを取れば出来ますが、面倒です！

# まとめ
HMDとかVR使える環境あれば、

1. 簡単に画像素材作れる
2. インパクトの大きい記事とか簡単にできる
3. 既存の素材があるなら、そちらの方がクオリティは高まる

漫画最初に作ろうと思いましたが、センスがなかったので断念しました。 +
素材作るだけじゃなく、センスも必要・・・私の漫画作成への道はまだ険しかったです。

おしまい。