= （編集中）最近ABテストで困ったこと
:hp-tags: sumomo, laravel, Response, beginner

こんにちわ、すももです。 +
よくサイト改善の為に、Google Optimize（以下、オプティマイズ）を使用してABテストを実施するのですが、 +
いつもやるABテストのやり方では上手くいかないパターンに出くわし、色々調べた結果Javascript使って解決したよって話です。 +
 +
【Google Optimizeとは】 +
https://ferret-plus.com/10561

例えば、フォーム画面のABテストで、デザイン変更と、 +
あと、プレースホルダの文言変えたり、項目の並び順ちょっと変えたいんだよな〜って時。 +
画像入れる +
 +

## よくやるABテストのパターンだと...？ +

```
<!-- 省略 -->
<style>
    .AB_test_B {
        display: none;
    }
</style>
</head>
<body>
    <form action="xxx" method="post" id="oreder_form" name="form">

        <!-- Aパターン(オリジナル版) -->
        <div class="AB_test_A">
            <p>Aパターン(オリジナル版)</p>
            <label for="company">会社名</label>
            <input type="text" name="company_name" placeholder="（例）株式会社イノベーション">
            <label for="name">お名前</label>
            <input type="text" name="name"  placeholder="（例）山田太郎">   
            <label for="tel">電話番号</label>
            <input type="tel" name="phone_number"  placeholder="（例）0312345678">
            <label for="address">住所</label>
            <div class="select">
                <select name="prefecture_id">
                    <option selected>お選びください</option>
                    <option value="1">北海道</option>
                    <option value="2">青森県</option>
                    <option value="3">秋田県</option>
                    <option value="4">岩手県</option>
                    <option value="5">山形県</option>
                    <option value="6">宮城県</option>
                    <option value="7">福島県</option>
                    <option value="8">※省略※</option>
                </select>
            </div>
            <input type="text" name="address" placeholder="市区町村以下(例:◯◯区✕✕ ◯◯-✕✕)">
        </div>

        <!-- Bパターン(改善版) -->
        <div class="AB_test_B">
            <p>Bパターン(改善版)</p>
            <input type="text" name="company_name" placeholder="会社名">
            <input type="text" name="name"  placeholder="お名前">
            <input type="tel" name="phone_number"  placeholder="電話番号">
            <div class="select">
                <select name="prefecture_id">
                    <option selected>所在地（都道府県）を選択</option>
                    <option value="1">北海道</option>
                    <option value="2">青森県</option>
                    <option value="3">秋田県</option>
                    <option value="4">岩手県</option>
                    <option value="5">山形県</option>
                    <option value="6">宮城県</option>
                    <option value="7">福島県</option>
                    <option value="8">※以下省略※</option>
                </select>
            </div>
            <input type="text" name="address" placeholder="所在地（市区町村以下）">
        </div>
        
        <!-- ※省略※ -->
    </form>
</body>
</html>
```

こんな感じで、ABどっちのパターンのコードも全部わーっと書いて、 +
`<div class="AB_test_A"></div>` とか `<div class="AB_test_B"></div>` でABテストの範囲を囲っとく。 +
通常はBパターン(改善版)をdisplay: none;で非表示にしといて、 +
Bパターン(改善版)を表示する際は、Aパターン(オリジナル版)をdisplay: none;に、Bパターン(改善版)をdisplay: block;になるよう +
オプティマイズで設定する、以上。 +
 +
おお、簡単だ！ +

## そしてこちらが、ABテストで困ったパターン... +

```
元コード書く
```

外部サービスを使用している都合上、指定のID(など)を変える事が出来ず、 +
いつものdisplay: none;で要素を非表示にする方法はダメ、 +
removeメソッドで要素自体を削除する方法も使えなかった。。 +
 +
周りに相談した結果、オプティマイズの設定でJavascript書いて、Bパターン(改善版)にだけ効かすことにしました〜 +

## 解決策 +







## 感想 +

いつものABテストのパターンより複雑になった為、このABテストの終了対応時はちょっと時間かかりそうですが、 +
オプティマイズの設定や、Javascriptのいい勉強になったので、結果良かったです！ +
 +
〜おわり〜 +